### PR TITLE
Rev7

### PR DESCRIPTION
**Pull request by adamglozik**

### CODE REVIEW

**Comment by jans23** [comment]
Thank you. What do we need the _rescue-backup_ folder and _nk-u2f-rescue.*_ files for? We have version control after all.

**Comment by jans23** [comment]
R3, 100 ohm, is lacking in the BOM.

**Comment by jans23** [comment]
As discussed, 100 ohm is too small. We tested with 390 ohm and the LED is sufficiently bright.

**Comment by szszszsz** [comment]
Is the change regarding the LED resistor added already to this PR?

**Comment by jans23** [comment]
Not yet.

**Pull request merged**
